export const slugify = (text: string) => {
  return text
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/à/g, "a")
    .replace(/á/g, "a")
    .replace(/â/g, "a")
    .replace(/ã/g, "a")
    .replace(/ā/g, "a")
    .replace(/å/g, "a")
    .replace(/æ/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ù/g, "u")
    .replace(/ú/g, "u")
    .replace(/û/g, "u")
    .replace(/ū/g, "u")
    .replace(/ß/g, "ss")
    .replace(/ò/g, "o")
    .replace(/ó/g, "o")
    .replace(/ô/g, "o")
    .replace(/õ/g, "o")
    .replace(/ō/g, "o")
    .replace(/ø/g, "o")
    .replace(/ì/g, "i")
    .replace(/í/g, "i")
    .replace(/î/g, "i")
    .replace(/ï/g, "i")
    .replace(/ī/g, "i")
    .replace(/è/g, "e")
    .replace(/é/g, "e")
    .replace(/ê/g, "e")
    .replace(/ë/g, "e")
    .replace(/ē/g, "e")
    .replace(/\(/g, "_")
    .replace(/\)/g, "_")
    .replace(/\s+/g, "-") // Replace spaces with hyphens
    .replace(/[^a-z0-9\-_]/g, ""); // Remove invalid characters
};
